const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const requireSchema = new Schema({
  RequiredPersonRole: {
    type: String,
    required: true,
    enum: ["Buyer", "Tenant", "Agent", "Builder"],
  },
  RequiredPersonName: { type: String, required: true },
  RequiredPersonPhone: { type: String, required: true },
  RequiredPersonEmail: { type: String, required: true },
  RequiredPropertyDetails: {
    RequiredPropertyType: {
      type: String,
      required: true,
      enum: ["Residential", "Commercial", "Industrial", "Plot&Land"],
    },
    RequiredAreaSqft: { min: { type: String }, max: { type: String } },
    RequiredBudget: { min: { type: String }, max: { type: String } },
    RequiredPropertySellOrRent: { type: String, enum: ["Sell", "Rent"] },
    RequiredConstructionStatus: {
      type: String,
      enum: [
        "New Launch",
        "Under Construction",
        "Ready to Move",
        "Old Construction",
      ],
    },
    RequiredDescription: { type: String },
  },
  AllResidential: {
    "Flat/Apartment": { type: Boolean },
    "High Rise Apartment": { type: Boolean },
    Bungalows: { type: Boolean },
    Penthouse: { type: Boolean },
    "Low Rise Apartment": { type: Boolean },
    "Row House": { type: Boolean },
    "Weekend Villas": { type: Boolean },
    "Farm House": { type: Boolean },
  },
  AllCommercial: {
    Office: { type: Boolean },
    Shop: { type: Boolean },
    Showroom: { type: Boolean },
    "Co Working Space": { type: Boolean },
    "Ready to Move Offices": { type: Boolean },
    Warehouse: { type: Boolean },
    "Cold Storage": { type: Boolean },
    Other: { type: Boolean },
  },
  CommercialAvailability: {
    BossCabin: { type: Boolean },
    ManagerCabin: { type: Boolean },
    WorkStation: { type: Boolean },
    Pantry: { type: Boolean },
    Reception: { type: Boolean },
    WaitingArea: { type: Boolean },
    CarParking: { type: Boolean },
  },
  AllIndustrial: {
    WareHouse: { type: Boolean },
    HeavyManufacturing: { type: Boolean },
    LightManufacturing: { type: Boolean },
    DistributionWarehouse: { type: Boolean },
    GeneralWarehouse: { type: Boolean },
    FlexSpace: { type: Boolean },
    ShowroomBuildings: { type: Boolean },
    ResearchAndDevelopment: { type: Boolean },
    DataCenter: { type: Boolean },
  },
  AllPlotAndLand: {
    ResidentialPlot: { type: Boolean },
    CommercialPlot: { type: Boolean },
    IndustrialPlot: { type: Boolean },
    AgricultureLand: { type: Boolean },
    NonAgricultureLand: { type: Boolean },
    ProjectLand: { type: Boolean },
  },
  Condition: {
    BuildingSite: { type: Boolean },
    StructuralFrameAndBuildingEnvelope: { type: Boolean },
    SemiFurnished: { type: Boolean },
    Roofing: { type: Boolean },
    Plumbing: { type: Boolean },
    Heating: { type: Boolean },
    AirConditioningAndVentilation: { type: Boolean },
    Electrical: { type: Boolean },
    VerticalTransportation: { type: Boolean },
    LifeSafetyFireProtection: { type: Boolean },
    InteriorElements: { type: Boolean },
    FullyFurnished: { type: Boolean },
    Furnished: { type: Boolean },
    SemiFurnished: { type: Boolean },
    KitchenFix: { type: Boolean },
    FixFurnished: { type: Boolean },
    Unfurnished: { type: Boolean },
  },
  ResidentialAvailability: {
    "1 Bhk": { type: Boolean },
    "2 Bhk": { type: Boolean },
    "3 Bhk": { type: Boolean },
    "4 Bhk": { type: Boolean },
    "5 Bhk": { type: Boolean },
    "6 Bhk": { type: Boolean },
    "Above 6Bhk": { type: Boolean },
  },
  ResidentAvailableFor: {
    forFamily: { type: Boolean },
    forExicutive: { type: Boolean },
    forBechlore: { type: Boolean },
  },
  Facing: {
    East: { type: Boolean },
    North: { type: Boolean },
    "North-East": { type: Boolean },
    "North-West": { type: Boolean },
    South: { type: Boolean },
    "South-East": { type: Boolean },
    "South-West": { type: Boolean },
    West: { type: Boolean },
  },
});
module.exports = mongoose.model("Requirement", requireSchema); //exporting the model
