const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const requireSchema = new Schema({
  RequiredPersonRole: {
    type: String,
    required: true,
    enum: ["Buyer", "Tenant", "Agent", "Builder"],
  },
  RequiredPersonName: { type: String, required: true },
  RequiredPersonPhone: { type: String, required: true },
  RequiredPersonEmail: { type: String, required: true },
  RequiredPropertyDetails: {
    RequiredPropertyType: {
      type: String,
      required: true,
      enum: ["Residential", "Commercial", "Industrial", "Plot&Land"],
    },
    RequiredAreaSqft: { min: { type: String }, max: { type: String } },
    RequiredBudget: { min: { type: String }, max: { type: String } },
    RequiredPropertySellOrRent: { type: String, enum: ["Sell", "Rent"] },
    RequiredConstructionStatus: {
      type: String,
      enum: [
        "New Launch",
        "Under Construction",
        "Ready to Move",
        "Old Construction",
      ],
    },
    RequiredDescription: { type: String },
  },
  AllResidential: {
    "Flat/Apartment": { type: Boolean },
    "High Rise Apartment": { type: Boolean },
    Bungalows: { type: Boolean },
    Penthouse: { type: Boolean },
    "Low Rise Apartment": { type: Boolean },
    "Row House": { type: Boolean },
    "Weekend Villas": { type: Boolean },
    "Farm House": { type: Boolean },
  },
  AllCommercial: {
    Office: { type: Boolean },
    Shop: { type: Boolean },
    Showroom: { type: Boolean },
    "Co Working Space": { type: Boolean },
    "Ready to Move Offices": { type: Boolean },
    Warehouse: { type: Boolean },
    "Cold Storage": { type: Boolean },
    Other: { type: Boolean },
  },
  CommercialAvailability: {
    "Boss Cabin": { type: Boolean },
    "Manager Cabin": { type: Boolean },
    "Work Station": { type: Boolean },
    Pantry: { type: Boolean },
    Reception: { type: Boolean },
    "Waiting Area": { type: Boolean },
    "Car Parking": { type: Boolean },
  },
  AllIndustrial: {
    "Ware House": { type: Boolean },
    "Heavy Manufacturing": { type: Boolean },
    "Light Manufacturing": { type: Boolean },
    "Distribution Warehouse": { type: Boolean },
    "General Warehouse": { type: Boolean },
    "Flex Space": { type: Boolean },
    "Showroom Buildings": { type: Boolean },
    "Research And Development": { type: Boolean },
    "Data Center": { type: Boolean },
  },
  AllPlotAndLand: {
    "Residential Plot": { type: Boolean },
    "Commercial Plot": { type: Boolean },
    "Industrial Plot": { type: Boolean },
    "Agriculture Land": { type: Boolean },
    "Non - Agriculture Land": { type: Boolean },
    "Project Land": { type: Boolean },
  },
  Condition: {
    "Building Site": { type: Boolean },
    "Structural Frame & Building Envelope": { type: Boolean },
    "Semi Furnished": { type: Boolean },
    Roofing: { type: Boolean },
    Plumbing: { type: Boolean },
    Heating: { type: Boolean },
    "Air Conditioning & Ventilation": { type: Boolean },
    Electrical: { type: Boolean },
    "Vertical Transportation (Elevators & Escalators)": { type: Boolean },
    "Life Safety / Fire Protection": { type: Boolean },
    "Interior Elements": { type: Boolean },
    "Fully Furnished": { type: Boolean },
    Furnished: { type: Boolean },
    "Semi Furnished": { type: Boolean },
    "Kitchen Fix": { type: Boolean },
    "Fix Furnished": { type: Boolean },
    Unfurnished: { type: Boolean },
  },
  ResidentialAvailability: {
    "1 Bhk": { type: Boolean },
    "2 Bhk": { type: Boolean },
    "3 Bhk": { type: Boolean },
    "4 Bhk": { type: Boolean },
    "5 Bhk": { type: Boolean },
    "6 Bhk": { type: Boolean },
    "Above 6Bhk": { type: Boolean },
  },
  ResidentAvailableFor: {
    "FOR FAMILY": { type: Boolean },
    "FOR EXICUTIVE": { type: Boolean },
    "FOR BECHLORE": { type: Boolean },
  },
  Facing: {
    East: { type: Boolean },
    North: { type: Boolean },
    "North-East": { type: Boolean },
    "North-West": { type: Boolean },
    South: { type: Boolean },
    "South-East": { type: Boolean },
    "South-West": { type: Boolean },
    West: { type: Boolean },
  },
});
module.exports = mongoose.model("Requirement", requireSchema); //exporting the model
